version: '2'

services:
  db:
    image: mysql
    container_name: gektar_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: username
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: dbname
    volumes:
      - ./db/data:/var/lib/mysql
    networks:
      - gektar

  web:
    image: nginx
    container_name: gektar_nginx
    restart: always
    ports:
      - "81:80"
    volumes:
      - ./app:/app
      - ./nginx/sites/${ENV}.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/${ENV}.default.conf:/etc/nginx/${ENV}.default.conf
    links:
      - php
    networks:
      - gektar

  php:
    container_name: gektar_php
    extends:
      file: base-php/base-php.yml
      service: base-php
    restart: always
    working_dir: /app
    volumes:
      - ./app:/app
    links:
      - db
    networks:
      - gektar

  phpmyadmin:
    container_name: gektar_phpmyadmin
    depends_on:
      - db
    image: phpmyadmin
    restart: always
    ports:
      - "8090:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: password
    networks:
      - gektar

networks:
  gektar:
    driver: bridge